// Generated by the WOLips Templateengine Plug-in at Jan 4, 2025 4:11:28 PM
package your.app;

import com.webobjects.appserver.WOApplication;
import com.webobjects.foundation.NSLog;
import com.webobjects.foundation._NSUtilities;

import your.app.components.Main;

public class Application extends WOApplication {
	public static void main(final String[] argv) {
		WOApplication.main(argv, Application.class);
	}

	public Application() {
		NSLog.out.appendln("Welcome to " + name() + " !");
		/* ** put your initialization code in here ** */
		setAllowsConcurrentRequestHandling(true);
		_NSUtilities.setClassForName(Session.class, Session.class.getSimpleName());
		_NSUtilities.setClassForName(Main.class, Main.class.getSimpleName());
	}
}
