// Generated by the WOLips Templateengine Plug-in at Jan 4, 2025 4:11:28 PM
package your.app;

import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
