// Generated by the WOLips Templateengine Plug-in at Jan 4, 2025 4:11:28 PM
package your.app.components;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {
	private static final long serialVersionUID = 1L;

	public Main(WOContext context) {
		super(context);
	}
}
